title: Pi Projects
description: A collection of Raspberry Pi projects

#### Enable line numbers in code blocks
highlighter: rouge
#
#rouge:
#  line_numbers: true
# 'true' turns the highlighter on for *all* code blocks
####

plugins:
  - jekyll-copy-code # puts a Copy button for code samples
